export const languagesExtensions = {
  "Agda": ".agda",
  "BF": ".bf",
  "C": ".c",
  "CFML": ".cfml",
  "Clojure": ".clojure",
  "COBOL": ".cobol",
  "CoffeeScript": ".coffee",
  "CommonLisp": ".lisp",
  "Coq": ".coq",
  "C++": ".cpp",
  "Crystal": ".cr",
  "C#": ".cs",
  "D": ".d",
  "Dart": ".dart",
  "Elixir": ".ex",
  "Elm": ".elm",
  "Erlang": ".erl",
  "Factor": ".factor",
  "Forth": ".fs",
  "Fortran": ".f90",
  "F#": ".fs",
  "Go": ".go",
  "Groovy": ".groovy",
  "Haskell": ".hs",
  "Haxe": ".hx",
  "Idris": ".idr",
  "Java": ".java",
  "JavaScript": ".js",
  "Julia": ".jl",
  "Kotlin": ".kt",
  "λ Calculus": ".lambda",
  "Lean": ".lean",
  "Lua": ".lua",
  "NASM": ".asm",
  "Nim": ".nim",
  "Objective-C": ".m",
  "OCaml": ".ml",
  "Pascal": ".pas",
  "Perl": ".pl",
  "PHP": ".php",
  "PowerShell": ".ps1",
  "Prolog": ".pl",
  "PureScript": ".purs",
  "Python": ".py",
  "R": ".r",
  "Racket": ".rkt",
  "Raku": ".rakumod",
  "Reason": ".re",
  "RISC-V": ".rv",
  "Ruby": ".rb",
  "Rust": ".rs",
  "Scala": ".scala",
  "Shell": ".sh",
  "Solidity": ".sol",
  "SQL": ".sql",
  "Swift": ".swift",
  "TypeScript": ".ts",
  "VB": ".vb",
  "SQLite 3.2.8": ".sqlite",
  "PostgreSQL 9.6": ".pgsql",
  "PostgreSQL 13.0": ".pgsql"
};
